-- 1. CREACIÓN Y USO
CREATE DATABASE MATRICULA;
USE MATRICULA;

-- 2. TABLA ALUMNO
CREATE TABLE ALUMNO (
    ID_ALUMNO INT AUTO_INCREMENT PRIMARY KEY,
    DNI_ALUMNO CHAR(8) UNIQUE NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    EDAD INT NOT NULL,
    GENERO CHAR(1) NOT NULL, -- 'M' o 'F'
    DIRECCION VARCHAR(100) NOT NULL,
    CELULAR CHAR(9) NOT NULL,
    CORREO VARCHAR(80) UNIQUE NOT NULL,
    ESTADO VARCHAR(10) DEFAULT 'ACTIVO',
    NOMBRE_APODERADO VARCHAR(50) NOT NULL,
    CELULAR_APODERADO CHAR(9) NOT NULL,
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABLA AULA
CREATE TABLE AULA (
    ID_AULA INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL VARCHAR(30) NOT NULL, -- 'Inicial', 'Primaria', 'Secundaria'
    GRADO INT NOT NULL,
    SECCION CHAR(1) NOT NULL,
    VACANTES_TOTALES INT NOT NULL,
    VACANTES_DISPONIBLES INT NOT NULL
);

-- 4. TABLA CURSO (Corregida a MAYÚSCULAS)
CREATE TABLE CURSO (
    ID_CURSO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    CREDITOS INT NOT NULL
);

-- 4.1 TABLA MATRICULA
CREATE TABLE MATRICULA (
    ID_MATRICULA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_AULA INT NOT NULL,
    ID_CURSO INT NOT NULL,
    FECHA_MATRICULA DATE NOT NULL,
    PERIODO VARCHAR(20),
    ESTADO VARCHAR(20) DEFAULT 'Activa',
    CODIGO VARCHAR(30) UNIQUE NOT NULL,
    FECHA_REGISTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_MATRICULA_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO) ON DELETE CASCADE,
    CONSTRAINT FK_MATRICULA_AULA FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA) ON DELETE CASCADE,
    CONSTRAINT FK_MATRICULA_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO) ON DELETE CASCADE
);

-- 4.1 TABLA CONFIGURACION
CREATE TABLE CONFIGURACION (
    ID_CONFIGURACION INT AUTO_INCREMENT PRIMARY KEY,
    CLAVE VARCHAR(100) UNIQUE NOT NULL,
    VALOR VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT
);

-- 5. TABLA USUARIO (Para el login administrativo)
CREATE TABLE USUARIO (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ESTADO TINYINT(1) DEFAULT 1
);

-- 6. TABLA RESERVA (Con llaves foráneas integradas)
CREATE TABLE RESERVA (
    ID_RESERVA INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUMNO INT NOT NULL,
    ID_AULA INT NOT NULL,
    CODIGO_PAGO VARCHAR(20) UNIQUE NOT NULL,
    FECHA_RESERVA DATETIME DEFAULT CURRENT_TIMESTAMP,
    ESTADO_PAGO VARCHAR(20) DEFAULT 'PENDIENTE',
    CONSTRAINT FK_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO) ON DELETE CASCADE,
    CONSTRAINT FK_AULA FOREIGN KEY (ID_AULA) REFERENCES AULA(ID_AULA) ON DELETE CASCADE
);

-- INSERCIÓN DE DATOS INICIALES (PARA PRUEBAS)

-- Aulas
INSERT INTO AULA (NIVEL, GRADO, SECCION, VACANTES_TOTALES, VACANTES_DISPONIBLES) VALUES 
('Secundaria', 3, 'A', 30, 5),
('Primaria', 1, 'A', 25, 25),
('Inicial', 5, 'A', 20, 10);

-- Cursos
INSERT INTO CURSO (NOMBRE, DESCRIPCION, CREDITOS) VALUES 
('Matemática', 'Cálculo y álgebra básica', 4),
('Programación', 'Desarrollo web con JS', 5),
('Base de Datos', 'Diseño SQL y optimización', 4);

-- Usuarios (Admin / mundo)
INSERT INTO USUARIO (USER_NAME, PASSWORD_HASH, ESTADO) 
VALUES ('Admin', '$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6', 1);

-- Alumnos (M y F para los gráficos del Dashboard)
INSERT INTO ALUMNO (DNI_ALUMNO, NOMBRES, APELLIDOS, FECHA_NACIMIENTO, EDAD, GENERO, DIRECCION, CELULAR, CORREO, NOMBRE_APODERADO, CELULAR_APODERADO, USER_NAME, PASSWORD_HASH) VALUES 
('45789865', 'Pepito', 'Rosales', '2004-05-15', 20, 'M', 'Av. Perú', '986532877', 'pepito@gmail.com', 'Sonia', '986532789', 'Pepito', 'mundo'),
('77441122', 'Maria', 'López', '2006-03-10', 18, 'F', 'Pro', '944552233', 'maria@gmail.com', 'Juan', '944556677', 'MariaL', '12345');

DESCRIBE alumno;

DELETE FROM ALUMNO WHERE DNI_ALUMNO IN ('45789865', '77441122');
 
-- 2. Insertar con los nombres de columna correctos (NOMBRE, APELLIDO)
INSERT INTO ALUMNO (
    DNI_ALUMNO, NOMBRE, APELLIDO,
    FECHA_NACIMIENTO, EDAD, GENERO,
    DIRECCION, CELULAR, CORREO,
    NOMBRE_APODERADO, CELULAR_APODERADO,
    USER_NAME, PASSWORD_HASH
) VALUES
(
    '45789865', 'Pepito', 'Rosales',
    '2004-05-15', 20, 'M',
    'Av. Perú', '986532877', 'pepito@gmail.com',
    'Sonia', '986532789',
    '45789865', '$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6'
),
(
    '77441122', 'Maria', 'Lopez',
    '2006-03-10', 18, 'F',
    'Pro', '944552233', 'maria@gmail.com',
    'Juan', '944556677',
    '77441122', '$2y$10$heuMG7aElXF5IiS4rCN49.T.smRQfhlCmVuoAh/SPpjQ6YA6qzZO6'
);
 
-- 3. Verificar
SELECT ID_ALUMNO, DNI_ALUMNO, NOMBRE, APELLIDO, ESTADO FROM ALUMNO;